server.port=8080
spring.application.name=blackjack

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.data.mongodb.uri=mongodb://localhost:27017/blackjack
spring.data.mongodb.database=blackjack
